# This is a basic workflow to help you get started with Actions

name: GList checker

# Controls when the workflow will run
on:
  # Triggers the workflow at 06:30 every day
  schedule:
    - cron: "30 6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Ping GList to check updates
        uses: satak/webrequest-action@master
        with:
          # Web request URL endpoint
          url: "https://glist.fly.dev/api/check"
          method: POST
          headers: '{"api-key": "${{ secrets.API_KEY }}"}'
